apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp-app
        image: wordpress
        env:
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: end321
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: wp-db
---
apiVersion: v1
kind: Service
metadata:
  name: wp-app
  labels:
    tier: frontend
    env: prod
    customer: tuke
spec: 
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: wp-app
