apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wp-db
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:      
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          value: top.secret
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_USER
          value: wpuser
        - name: MARIADB_PASSWORD
          value: end321
        image: mariadb
        name: wp-db    
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db
  namespace: wordpress
  labels:
    tier: backend
    env: prod
    customer: tuke
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:  
    app: wp-db
